project:
  type: website
  output-dir: docs

website:
  title: "Maya G T Ogonah"
  navbar:
    left:
      - text: "Brief CV"
        href: cv.qmd
      - text: "Research"
        href: research.qmd
      - text: "Talks"
        href: talks.qmd
      - text: "Repositories"
        href: programming.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


plugins: jekyll-redirect-from