---
title: " "
pagetitle: "Maya G T Ogonah"
---

<link rel="stylesheet" href="styles.css" type="text/css">

<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/jpswalsh/academicons@1/css/academicons.min.css">

### Brief CV

#### **Research experience**

- 2025-2027: Postdoctoral Research Scientist at Columbia University (NYC, United States);

- 2021-2025: DPhil Candidate at the University of Oxford (Oxford, United Kingdom);

- 2024-2025: Academic Tutor at the University of Georgia at Oxford Programme (Oxford, United Kingdom);

- 2021: Charity Research Intern at Hope for Children (Remote);

- 2021: Health Data Research Intern at University College London Institute of Informatics (London, United Kingdom);

- 2020: Honorary Assistant Psychologist at Maudsley Simulation and Learning (London, United Kingdom)

#### **Education**

- 2025: DPhil in Psychiatry from [University of Oxford](https://www.ox.ac.uk/admissions/graduate/courses/dphil-psychiatry). DPhil dissertation *"Violence Perpetration, Victimisation, and Self-Harm in Traumatic Brain Injury An Evidence Synthesis, Epidemiological, and Risk Modelling Approach"* is available [here](https://ora.ox.ac.uk/objects/uuid:f6872374-96f6-4a32-ab60-364abaefb8cb).

- 2021: Bachelors of Science (Hons) in Psychology from [King's College London](https://www.kcl.ac.uk/study/undergraduate/courses/psychology-bsc). BSc dissertation *"Evaluating School-Type Effects on Intellectual Humility: Does the Prevalence of Psychopathic Traits Partially Explain the Relationship?"*

#### **Awards**

- 2026: 2026-27 AAUW American Postdoctoral Research Leave Fellowship, American Association of University Women ($50,000)

- 2026: Alwyn Lishman Prize, British Neuropsychiatry Association (£250)

- 2025: Vice Chancellor’s Excellence Across Oxford: Commitment to Equality, Diversity, and Inclusion Award, University of Oxford

- 2024: Travel Award, Guarantors of the Brain (£600)

- 2024: Academic Activity Award, Linacre College (£300)

- 2024: Race Equality Recognition Award, Department of Psychiatry, University of Oxford

- 2021: Academic Futures Oxford Graduate Scholarship for DPhil study, University of Oxford (course fees and stipend)