---
title: " "
pagetitle: "Maya G T Ogonah"
---

<link rel="stylesheet" href="styles.css" type="text/css">

<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/jpswalsh/academicons@1/css/academicons.min.css">

### Selected publications  
  
#### Traumatic brain injury 

**Ogonah, M.G.T**, Botchway, S., Yu, R., Schofield, P., & Fazel, S (2025). An umbrella review of health outcomes following traumatic brain injury. *Nature Mental Health*. [https://doi.org/10.1038/s44220-024-00356-5](https://doi.org/10.1038/s44220-024-00356-5)

**Ogonah, M.G.T**. & Botchway, S. (2025) Research Briefing: Physical and mental health after traumatic brain injury. *Nature Mental Health*. [https://doi.org/10.1038/s44220-024-00362-7](https://doi.org/10.1038/s44220-024-00362-7) [Research Briefing]
  
#### Risk prediction 

Seyedsalehi A., Bailey, J., **Ogonah, M. G. T.**, Fanshawe, T. R., & Fazel, S. (2025) Prediction models for self-harm and suicide: a systematic review and critical appraisal. *BMC Medicine*, 23(549). [https://doi.org/10.1186/s12916-025-04367-6](https://doi.org/10.1186/s12916-025-04367-6)

**Ogonah, M. G. T.**, Seyedalehi, A., Whiting, D., & Fazel, S. (2023). Violence risk assessment instruments in forensic psychiatric populations: A systematic review and meta-analysis of their performance. *The Lancet Psychiatry*, 10, 780-789. [https://doi.org/10.1016/S2215-0366(23)00256-0](https://doi.org/10.1016/S2215-0366(23)00256-0)

#### Simulation training

**Ogonah M. G. T.**, Vega, M. O., Valdearenas, L., Cross, S., & Attoe, C. (2021). Mental health crises in the emergency department: simulation training for interprofessional collaboration and teamwork attitudes. *International Journal of Healthcare Simulation*, 1(1), 11-27. [https://www.ijohs.com/article/doi/10.54531/OWXJ2519](https://www.ijohs.com/article/doi/10.54531/OWXJ2519)







